// <auto-generated />
using System;
using ERPToolsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tools.Migrations
{
    [DbContext(typeof(ERPToolsDbContext))]
    [Migration("20250926072255_Envelopemaking")]
    partial class Envelopemaking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERPToolsAPI.Models.ExcelUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catch")
                        .HasColumnType("longtext");

                    b.Property<string>("Course")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamType")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("PaperNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExcelUploads");
                });

            modelBuilder.Entity("ERPToolsAPI.Models.UserLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLoginLogs");
                });

            modelBuilder.Entity("Tools.Models.BoxCapacity", b =>
                {
                    b.Property<int>("BoxCapacityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BoxCapacityId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("BoxCapacityId");

                    b.ToTable("BoxCapacity");
                });

            modelBuilder.Entity("Tools.Models.EnvelopeBreakage", b =>
                {
                    b.Property<int>("EnvelopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnvelopeId"));

                    b.Property<string>("InnerEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NrDataId")
                        .HasColumnType("int");

                    b.Property<string>("OuterEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TotalEnvelope")
                        .HasColumnType("int");

                    b.HasKey("EnvelopeId");

                    b.ToTable("EnvelopeBreakages");
                });

            modelBuilder.Entity("Tools.Models.EnvelopeType", b =>
                {
                    b.Property<int>("EnvelopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnvelopeId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("EnvelopeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EnvelopeId");

                    b.ToTable("EnvelopesTypes");
                });

            modelBuilder.Entity("Tools.Models.ExtraEnvelopes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatchNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.Property<string>("InnerEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OuterEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExtrasEnvelope");
                });

            modelBuilder.Entity("Tools.Models.ExtraType", b =>
                {
                    b.Property<int>("ExtraTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExtraTypeId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExtraTypeId");

                    b.ToTable("ExtraType");
                });

            modelBuilder.Entity("Tools.Models.ExtrasConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnvelopeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtraType")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExtraConfigurations");
                });

            modelBuilder.Entity("Tools.Models.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<bool>("IsUnique")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FieldId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Tools.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Tools.Models.NRData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatchNo")
                        .HasColumnType("longtext");

                    b.Property<string>("CenterCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamTime")
                        .HasColumnType("longtext");

                    b.Property<string>("NRDatas")
                        .HasColumnType("longtext");

                    b.Property<string>("NodalCode")
                        .HasColumnType("longtext");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NRDatas");
                });

            modelBuilder.Entity("Tools.Models.ProjectConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxBreakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnvelopeMakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectConfigs");
                });

            modelBuilder.Entity("Tools.Models.ToolConfig", b =>
                {
                    b.Property<int>("ToolConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ToolConfigId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ToolConfigId");

                    b.ToTable("ToolConfigs");
                });

            modelBuilder.Entity("Tools.Models.ToolRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ToolRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
