// <auto-generated />
using System;
using ERPToolsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tools.Migrations
{
    [DbContext(typeof(ERPToolsDbContext))]
    [Migration("20260610120448_AddStatusToBreakingResults")]
    partial class AddStatusToBreakingResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERPToolsAPI.Models.ExcelUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catch")
                        .HasColumnType("longtext");

                    b.Property<string>("Course")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamType")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("PaperNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExcelUploads");
                });

            modelBuilder.Entity("ERPToolsAPI.Models.UserLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLoginLogs");
                });

            modelBuilder.Entity("Tools.Models.BoxBreakingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookletSerial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BoxNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<int?>("EnvelopeBreakingResultId")
                        .HasColumnType("int");

                    b.Property<int?>("InnerBundlingSerial")
                        .HasColumnType("int");

                    b.Property<string>("OmrSerial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.Property<int>("UploadBatch")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BoxNo");

                    b.ToTable("BoxBreakingResults");
                });

            modelBuilder.Entity("Tools.Models.BoxCapacity", b =>
                {
                    b.Property<int>("BoxCapacityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BoxCapacityId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("BoxCapacityId");

                    b.ToTable("BoxCapacity");
                });

            modelBuilder.Entity("Tools.Models.ChangedNRData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatchNo")
                        .HasColumnType("longtext");

                    b.Property<string>("CenterCode")
                        .HasColumnType("longtext");

                    b.Property<double>("CenterSort")
                        .HasColumnType("double");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamTime")
                        .HasColumnType("longtext");

                    b.Property<string>("NRDatas")
                        .HasColumnType("longtext");

                    b.Property<int>("NRQuantity")
                        .HasColumnType("int");

                    b.Property<string>("NodalCode")
                        .HasColumnType("longtext");

                    b.Property<double>("NodalSort")
                        .HasColumnType("double");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<int>("RouteSort")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChangedNRData");
                });

            modelBuilder.Entity("Tools.Models.ConflictingFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConflictingField")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NRDataId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UniqueField")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ConflictingFields");
                });

            modelBuilder.Entity("Tools.Models.EnvelopeBreakage", b =>
                {
                    b.Property<int>("EnvelopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnvelopeId"));

                    b.Property<string>("InnerEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NrDataId")
                        .HasColumnType("int");

                    b.Property<string>("OuterEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TotalEnvelope")
                        .HasColumnType("int");

                    b.HasKey("EnvelopeId");

                    b.HasIndex("NrDataId", "ProjectId")
                        .IsUnique();

                    b.ToTable("EnvelopeBreakages");
                });

            modelBuilder.Entity("Tools.Models.EnvelopeBreakingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookletSerial")
                        .HasColumnType("longtext");

                    b.Property<string>("CatchNo")
                        .HasColumnType("longtext");

                    b.Property<string>("CenterCode")
                        .HasColumnType("longtext");

                    b.Property<int>("CenterEnv")
                        .HasColumnType("int");

                    b.Property<double>("CenterSort")
                        .HasColumnType("double");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<int>("DistrictSort")
                        .HasColumnType("int");

                    b.Property<string>("Env")
                        .HasColumnType("longtext");

                    b.Property<string>("EnvQuantity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExamDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamTime")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExtraId")
                        .HasColumnType("int");

                    b.Property<string>("NodalCode")
                        .HasColumnType("longtext");

                    b.Property<double>("NodalSort")
                        .HasColumnType("double");

                    b.Property<int>("NrDataId")
                        .HasColumnType("int");

                    b.Property<string>("OmrSerial")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<int>("RouteSort")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TotalEnv")
                        .HasColumnType("int");

                    b.Property<int>("UploadBatch")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnvelopeBreakingResults");
                });

            modelBuilder.Entity("Tools.Models.EnvelopeType", b =>
                {
                    b.Property<int>("EnvelopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnvelopeId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("EnvelopeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EnvelopeId");

                    b.ToTable("EnvelopesTypes");
                });

            modelBuilder.Entity("Tools.Models.ErrorLog", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ErrorId"));

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Occurance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ErrorId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Tools.Models.EventLog", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventTriggeredBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("Tools.Models.ExtraEnvelopes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatchNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.Property<string>("InnerEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NodalCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OuterEnvelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodalCode", "ExtraId", "ProjectId")
                        .IsUnique();

                    b.ToTable("ExtrasEnvelope");
                });

            modelBuilder.Entity("Tools.Models.ExtraType", b =>
                {
                    b.Property<int>("ExtraTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExtraTypeId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExtraTypeId");

                    b.ToTable("ExtraType");
                });

            modelBuilder.Entity("Tools.Models.ExtrasConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnvelopeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtraType")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RangeConfig")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nodalValue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExtraType", "ProjectId")
                        .IsUnique();

                    b.ToTable("ExtraConfigurations");
                });

            modelBuilder.Entity("Tools.Models.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<bool>("IsUnique")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FieldId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Tools.Models.MExtraConfigurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnvelopeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExtraType")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RangeConfig")
                        .HasColumnType("longtext");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MExtraConfigurations");
                });

            modelBuilder.Entity("Tools.Models.MProjectConfigs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookletSerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("BoxBreakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BoxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<string>("DuplicateCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DuplicateRemoveFields")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Enhancement")
                        .HasColumnType("double");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnvelopeMakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InnerBundlingCriteria")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsInnerBundlingDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OmrSerialNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("ResetBookletSerialOnCatchChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetOmrSerialOnCatchChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetOnSymbolChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SortingBoxReport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MProjectConfigs");
                });

            modelBuilder.Entity("Tools.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentModuleIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Tools.Models.Mss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MssType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mss");
                });

            modelBuilder.Entity("Tools.Models.NRData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatchNo")
                        .HasColumnType("longtext");

                    b.Property<string>("CenterCode")
                        .HasColumnType("longtext");

                    b.Property<double>("CenterSort")
                        .HasColumnType("double");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<string>("Day")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<int>("DistrictSort")
                        .HasColumnType("int");

                    b.Property<int>("EnvLotNo")
                        .HasColumnType("int");

                    b.Property<string>("ExamDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ExamTime")
                        .HasColumnType("longtext");

                    b.Property<int>("LotNo")
                        .HasColumnType("int");

                    b.Property<int?>("NRDataId")
                        .HasColumnType("int");

                    b.Property<string>("NRDatas")
                        .HasColumnType("longtext");

                    b.Property<int>("NRQuantity")
                        .HasColumnType("int");

                    b.Property<string>("NodalCode")
                        .HasColumnType("longtext");

                    b.Property<double>("NodalSort")
                        .HasColumnType("double");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<int>("RouteSort")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.Property<string>("UploadList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NRDatas");
                });

            modelBuilder.Entity("Tools.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserAssigned")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tools.Models.ProjectConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookletSerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("BoxBreakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BoxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<string>("DuplicateCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DuplicateRemoveFields")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Enhancement")
                        .HasColumnType("double");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnvelopeMakingCriteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InnerBundlingCriteria")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsInnerBundlingDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MssAttached")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MssTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OmrSerialNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool?>("ResetBookletSerialOnCatchChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetOmrSerialOnCatchChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetOnSymbolChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RoundOffBeforeEnhancement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SortingBoxReport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectConfigs");
                });

            modelBuilder.Entity("Tools.Models.RPTMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MappingJson")
                        .HasColumnType("longtext");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("RPTMappings");
                });

            modelBuilder.Entity("Tools.Models.RPTTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignSnapshotJson")
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModuleIds")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsedFieldsJson")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RPTFilePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("ReportStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredFieldsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.ToTable("RPTTemplates");
                });

            modelBuilder.Entity("Tools.Models.ToolConfig", b =>
                {
                    b.Property<int>("ToolConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ToolConfigId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ToolConfigId");

                    b.ToTable("ToolConfigs");
                });

            modelBuilder.Entity("Tools.Models.ToolRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ToolRecords");
                });

            modelBuilder.Entity("ToolsAPI.Models.EnvelopeLotReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnvLotNumbers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EnvelopeLotReports");
                });

            modelBuilder.Entity("ToolsAPI.Models.EnvelopeLotReport", b =>
                {
                    b.HasOne("Tools.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
